# Generated by Django 2.2.3 on 2019-07-08 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='flat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='flat', to='core.Flat'),
        ),
    ]
