# Generated by Django 2.2.3 on 2019-07-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190706_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixture',
            old_name='flatID',
            new_name='flatId',
        ),
        migrations.RenameField(
            model_name='flat',
            old_name='buildingID',
            new_name='buildingId',
        ),
        migrations.AddField(
            model_name='fixture',
            name='priceValue',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flat',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
    ]
