# Generated by Django 2.2.3 on 2019-07-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190706_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isStaff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='isSuperuser',
            field=models.BooleanField(default=False),
        ),
    ]
