# Generated by Django 2.2.3 on 2019-07-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190708_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixture',
            old_name='room',
            new_name='room_id',
        ),
    ]
