# Generated by Django 2.2.3 on 2019-07-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190706_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='isDelete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='fixture',
            old_name='flatId',
            new_name='flat_id',
        ),
        migrations.RenameField(
            model_name='fixture',
            old_name='isDelete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='fixture',
            old_name='priceValue',
            new_name='price_value',
        ),
        migrations.RenameField(
            model_name='flat',
            old_name='buildingId',
            new_name='building_id',
        ),
        migrations.RenameField(
            model_name='flat',
            old_name='isDelete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='isStaff',
            new_name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isSuperuser',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
