# Generated by Django 2.2.3 on 2019-07-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190706_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='price_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
