# Generated by Django 2.2.3 on 2019-07-09 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190708_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Room'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='building_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Building'),
        ),
        migrations.AlterField(
            model_name='room',
            name='flat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Flat'),
        ),
    ]
